modLoader = "javafml" #mandatory
loaderVersion = "[37.0,)" #mandatory
issueTrackerURL = "https://github.com/afjl1919/Ice_and_Fire_modify/issues" #optional
license = "GNU LESSER GENERAL PUBLIC LICENSE"
[[mods]] #mandatory
modId = "iceandfire" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Ice and Fire modify" #mandatory
authors = "Raptorfarian and Alexthe666. Modified by afjl1919"
description = '''Dragons and other mythological creatures in minecraft.'''
[[dependencies.iceandfire]] #optional
modId = "citadel" #mandatory
mandatory = true #mandatory
versionRange = "[2.4.1,)" #mandatory
ordering = "AFTER"
side = "BOTH"
[[dependencies.iceandfire]]
    modId = "forge"
    mandatory = true
    versionRange="[40.3.0,)"
    side="BOTH"